### ISSUE TITLE
Add ability to specify different rate limit per auth and anonymous users 

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#123]
The goal of this ticker is to provide the ability to define two different rate limits both for authenticated users and anonymous users, both for build and pull requests 

Ideally, those settings should be provided by the configuration file as shown below

```
rate-limit:
  build:
    anonymous: "10 / 1 hour"
    authenticated: "10 / 1 min" 
  pull:
    anonymous: "100 / 1 hour"
    authenticated: "100 / 1 min" 
```

It would be fair to include IP address of the requesting user when the request originates from an anonymous user, otherwise, multiple request from different anonymous users would receive the same rate-limit key.
