### ISSUE TITLE
Instrument micrometer to send percentiles for controller latencies

### ISSUE THREAD

**Issue by swampie** [seqeralabs/wave#232]
## Description

In order to calculate average latency of the endpoint the percentile metrics are needed to have a better precision in the dashboards.
This is easily doable by adding the following snippets into the application-prometheus.yml 

```
micronaut:
  metrics:
    binders:
      web:
        server:
          percentiles: "0.95,0.99"
        client:
          percentiles: "0.95,0.99"
```
Use "0.999, 0.99, 0.95, 0.50" as percentiles
