### ISSUE TITLE
Env variables in the config file are not resolved

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#40]
I'm trying to use some env variables in the application-dev.yml file, eg. 

```
  registries:
    - name: docker.io
      host: registry-1.docker.io
      auth:
        username: ${DOCKER_USER}
        password: ${DOCKER_PAT}
```

However, it looks the are not resolved (see below). Not understanding the reason, we are heavily using this notation on Tower 

```
21:33:05.341 [default-nioEventLoopGroup-1-2] DEBUG io.seqera.controller.V2Controller - Server configuration=DefaultConfiguration[arch=x86_64; registries=Registry[name=docker.io; host=registry-1.docker.io; auth=Auth[service=registry.docker.io; username=${DOCKER_USER}; password=${D****; url=auth.docker
```
