### ISSUE TITLE
[Feature] Download Singularity image without having `singularity` installed locally

### ISSUE THREAD

**Issue by ewels** [seqeralabs/wave#443]
It would be great to be able to download Singularity / Apptainer images as flat files, without needing to have the tools installed locally.

According to @pditommaso:

> it should be doable resolving the url of the tar file uploaded in the oci repo

🤞🏻

**Comment by pditommaso** [comment]
Ta da!

```
» wave -i oras://docker.io/pditommaso/wave-test:bamtools-2.5.2--5027ffe85d788a97 --inspect -o yaml

container:
  config:
    architecture: null
    config:
      attachStderr: null
      attachStdin: null
      attachStdout: null
      cmd: &id001 []
      domainName: null
      entrypoint: *id001
      env: *id001
      hostName: null
      image: null
      tty: null
      user: null
      workingDir: null
    container: null
    created: null
    rootfs:
      diff_ids: *id001
      type: null
  digest: sha256:c1540f55fa91f1070ca442ebc56c156e1f60b18faf09b0f3c3df4518be206f7d
  hostName: https://registry-1.docker.io
  imageName: pditommaso/wave-test
  manifest:
    annotations: null
    config:
      annotations: null
      digest: sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
      mediaType: application/vnd.unknown.config.v1+json
      size: 2
    layers:
    - annotations:
        org.opencontainers.image.title: image.sif
      digest: sha256:3b1bcd5a2806a49b1150f408853513ee33bda417804c9e26ac348d566ab1d8b8
      mediaType: application/vnd.sylabs.sif.layer.v1.sif
      size: 44986368
      uri: https://registry-1.docker.io/v2/pditommaso/wave-test/blobs/sha256:3b1bcd5a2806a49b1150f408853513ee33bda417804c9e26ac348d566ab1d8b8
    mediaType: null
    schemaVersion: 2
  reference: bamtools-2.5.2--5027ffe85d788a97
  registry: docker.io
```
