### ISSUE TITLE
Add page to render container inspect metadata

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#599]
Wave provides an inspect capability that summarise keys container images metadata e.g. config, layers checksum, image digest. etc. 

```
» wave --inspect -i ubuntu -o yaml
container:
  config:
    architecture: amd64
    config:
      attachStderr: false
      attachStdin: false
      attachStdout: false
      cmd:
      - /bin/bash
      domainName: null
      entrypoint: []
      env:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      hostName: null
      image: sha256:5333392d4deeb70ab614d13914296b3ed15740bbf2c6e8557d681bc451013010
      tty: false
      user: null
      workingDir: null
    container: 9e2f0a4a3e3829e7bf3c12134cfd03238aec6ca2ce5029cf0197627a3b37621e
    created: '2024-06-07T12:00:09.099611108Z'
    rootfs:
      diff_ids:
      - sha256:a30a5965a4f7d9d5ff76a46eb8939f58e95be844de1ac4a4b452d5d31158fdea
      type: layers
  digest: sha256:2e863c44b718727c860746568e1d54afd13b2fa71b160f5cd9058fc436217b30
  hostName: https://registry-1.docker.io
  imageName: library/ubuntu
  manifest:
    annotations: null
    config:
      annotations: null
      digest: sha256:35a88802559dd2077e584394471ddaa1a2c5bfd16893b829ea57619301eb3908
      mediaType: application/vnd.oci.image.config.v1+json
      size: 2296
    layers:
    - annotations: null
      digest: sha256:9c704ecd0c694c4cbdd85e589ac8d1fc3fd8f890b7f3731769a5b169eb495809
      mediaType: application/vnd.oci.image.layer.v1.tar+gzip
      size: 29705153
      uri: https://registry-1.docker.io/v2/library/ubuntu/blobs/sha256:9c704ecd0c694c4cbdd85e589ac8d1fc3fd8f890b7f3731769a5b169eb495809
    mediaType: application/vnd.oci.image.manifest.v1+json
    schemaVersion: 2
  reference: latest
  registry: docker.io
```

The goal of this issue is to a view in the [ViewController](https://github.com/seqeralabs/wave/blob/8a1c32767dc09bb50c827a44487f5d3864bb6f8c/src/main/groovy/io/seqera/wave/controller/ViewController.groovy#L48-L48) to render the above metadata for a given container image as a HTML page. 

Ideally it should be organised in the following top entries: 

* imageName
* reference (tag)
* digest
* registry 
* hostName
* config
* manifest
