### ISSUE TITLE
Add the support for shared file system when using K8s build backend

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#92]
The build via K8s backend currently uses an host mount to access the container [build context directory](http://github.com/seqeralabs/wave/blob/3b24fbad8f0b9700e31bf26525057256c0f0e211/src/main/groovy/io/seqera/wave/service/builder/BuildRequest.groovy#L36-L36). See [here](http://github.com/seqeralabs/wave/blob/3b24fbad8f0b9700e31bf26525057256c0f0e211/src/main/groovy/io/seqera/wave/service/k8s/K8sServiceImpl.groovy#L142-L142).

However this only forks for dev purposes. In a production deployment the Wave pod and the build pod are expected to share the build context via AWS EFS file system accessed by both pods. 

The goal of this issue is to modify the build pod specified to add the support for the creation of a volume claim mount as it's done in the Wave pod. e.g. 

```
          volumeMounts:
            - name: "vol-data"
              mountPath: "/work"
      volumes:
        - name: vol-data
          persistentVolumeClaim:
            claimName: wave-logs
```

### Constraints : 

* both wave and the build pods should use the same persistentVolumeClaim and mount path 
* the [build work dir](http://github.com/seqeralabs/wave/blob/3b24fbad8f0b9700e31bf26525057256c0f0e211/src/main/groovy/io/seqera/wave/service/builder/BuildRequest.groovy#L36-L36) should be a subdirectory of such mount path
* the build pod mount `subPath` should be relative path of root mount path and the request build directory
